### ISSUE TITLE
[Bug]: Adding query() triggers warning of Incompatible return type

### ISSUE THREAD

**Issue by buzkall** [laravel-idea/plugin#1266]
### Bug description

In a Laravel model, when running an Eloquent query, if I add the function query(), I get the warning of incompatible type suggesting that the return type should be the Laravel idea helper file.

![Image](https://github.com/user-attachments/assets/a3c1c022-a379-4988-a09b-b701229a7e06)

### Plugin version

11.3.0.252

### Operating system

MacOS

### Steps to reproduce

Removing the query() from the function eliminates the warning

### Relevant log output

```shell

```

**Comment by adelf** [comment]
Hello. What is `module()`? Scope? Could you provide the model code?

**Comment by buzkall** [comment]
Yes, module() is a scope.

Here I attach a simpler example with the code of the scope

![Image](https://github.com/user-attachments/assets/0e3c049d-6557-4bc3-910d-9047f68bc4aa)

With the #[Scope] approach I need to add query() or I'll get an error "Non-static method App\Models\Center::installed() cannot be called statically"

The same warning happens if I use the older scope prefix

![Image](https://github.com/user-attachments/assets/ff0749d1-24ed-4d61-a154-a40cda53c0aa)

**Comment by adelf** [comment]
Hello. Reproduced. It appeared in the last PhpStorm update. We will try to fix.

**Comment by adelf** [comment]
Fixed in 11.4. It should disappear after helper code generation with 11.4

**Comment by buzkall** [comment]
I'm on the Laravel Idea plugin version 11.4.1.252, I've executed the "Generate helper code" function, but I still get the same warning if I set Illuminate\Support\Collection as the return value

![Image](https://github.com/user-attachments/assets/dd5b84c0-5edf-4e9d-b79a-d4b72c813d34)

![Image](https://github.com/user-attachments/assets/d9db524b-f7b4-4040-8732-87602c6978f0)

**Comment by adelf** [comment]
Could you try to run main menu -> FIle > Invalidate Caches... and after that generate helper code again. I got the warning once, but after that, the helper code works ok. Seems, we have a floating bug here... And seems, It's not inside Laravel Idea. It asks PhpStorm about the type of some methods and get dfferent results...

**Comment by buzkall** [comment]
I've invalidaded caches and generated code again, but the same warning keeps appearing 😭

**Comment by adelf** [comment]
We are sorry about this. We are going to fully rewrite the helper code generation part in 12.0, and probably will fix this there.
