### ISSUE TITLE
[Bug]: Multiple definitions exist for class 'xxxxx' in PhpStorm

### ISSUE THREAD

**Issue by michabbb** [laravel-idea/plugin#745]
### Bug description

![image](https://user-images.githubusercontent.com/3524595/227448636-9ac3f19a-fca0-40b9-854d-28c0d8f0d3a6.png)
![image](https://user-images.githubusercontent.com/3524595/227448658-93751412-5cc3-427a-bde6-08accc2127f8.png)

### Plugin version

7.0.0.231

### Operating system

Linux

### Steps to reproduce

see screenshot

is there a way to avoid these "duplicate messages" ???

thanks

**Comment by adelf** [comment]
Should be fixed in 7.0.1. Thanks.

**Comment by michabbb** [comment]
@adelf sorry, i am using 7.0.1.231 and still see that message. is there anything I have to clear/reset?
i already recompiled the helper code. thanks!

**Comment by adelf** [comment]
That's strange. When you Cmd-click on the class name - does it still show multiple declarations in the macro and facades helper classes?

**Comment by michabbb** [comment]
yes, sorry. in case it helps, i am using "Str" in the "AppServiceProdivder.php", here´s the code of the generated helper files:

_ide_helper_macro.php

```php
namespace  {
    
    /**
     * @method string truncateWords(string $text, int $max, string $tail = '')
     */
    class Str {}
}
```

_ide_helper_facades.php

```php
namespace {
  // ..............
    class Str extends Illuminate\Support\Str {}
   // ..............
}
```

_ide_helper_macro_static.php

```php
namespace  {
    
    /**
     * @method static string truncateWords(string $text, int $max, string $tail = '')
     */
    class Str {}
}
```

**Comment by adelf** [comment]
Fixed in Laravel Idea 10.
